DROP DATABASE if EXISTS PESTO;
CREATE DATABASE PESTO;

USE PESTO;

-- creating TABLE cities
DROP TABLE if EXISTS CITIES;
CREATE TABLE CITIES(
    id int PRIMARY KEY,
    city VARCHAR(20) NOT NULL,
    state VARCHAR(20) NOT NULL
);

-- creating TABLE customer
DROP TABLE if EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(
    cno int PRIMARY KEY,
    cname VARCHAR(50) NOT NULL,
    addr VARCHAR(50),
    cu_city VARCHAR(20) 
);

--creating TABLE WAREHOUSES
DROP TABLE if EXISTS WAREHOUSES;
CREATE TABLE WAREHOUSES(
    WID int PRIMARY KEY,
    WNAME char(30),
    LOCATION char(20),
    EXTRACONTEXT json
);

--creating TABLE warehouses
DROP TABLE if EXISTS STORES;
CREATE TABLE STORES(
    SID int PRIMARY key,
    STORE_NAME char(20),
    LOCATION_CITY char(20)
);

--creating TABLE ORDERS
DROP TABLE if EXISTS ORDERS;
CREATE TABLE ORDERS(
    ONO int PRIMARY key,
    ODATE date
);

--creating TABLE ITEMS
DROP TABLE is EXISTS ITEMS;
CREATE TABLE ITEMS(
    ITEMNO int PRIMARY KEY,
    DESCRIPTION text,
    WEIGHT decimal(5,2),
    COST decimal(5,2)
);